Rails:
  Enabled: true

AllCops:
  TargetRailsVersion: 5.1
  TargetRubyVersion: 2.5
  Exclude:
  - 'Rakefile'
  - 'spec/dummy/**/*'
  - 'vendor/bundle/**/*'
  - 'bin/**/*'
  - 'log/**/*'
  - 'tmp/**/*'
  - 'db/**/*'
  - 'lib/generators/solidus_simple_sale_price/install/install_generator.rb'

Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
  - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
  - 'Gemfile'

Style/FrozenStringLiteralComment:
  Enabled: false

